version: '2'

services:
  web:
    build: .
    image: healthcheck:crontest
    working_dir: /app
    command: python3 manage.py runserver 0.0.0.0:4000
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    links:
      - mysql
  mysql:
    container_name: "mysql_healthcheck"
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=hc
      - MYSQL_USER=healthy
      - MYSQL_PASSWORD=ldf@health123
      - MYSQL_ROOT_PASSWORD=lbr123
    volumes:
      - ./data:/var/lib/mysql
    command: ["mysqld"]
    ports:
      - "3306:3306"
    expose:
      - "3306"